### ISSUE TITLE
구글 드라이버를 막았는데 더 이상 못 쓰는건가요?

### ISSUE THREAD

**Issue by min0224** [kimjunsung04/classcard_auto#16]
Traceback (most recent call last):
  File "D:\Desktop\github\classcard_auto\main.py", line 39, in <module>
  File "selenium\webdriver\remote\webdriver.py", line 741, in find_element
  File "selenium\webdriver\remote\webdriver.py", line 347, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 228, in check_response
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: 클래스카드는 Chrome 또는 Safari 브라우저를 사용 하세요
Message: unexpected alert open: {Alert text : 클래스카드는 Chrome 또는 Safari 브라우저를 사용하세요}
  (Session info: chrome=123.0.6312.86)
Stacktrace:
        GetHandleVerifier [0x00007FF6458170C2+63090]
        (No symbol) [0x00007FF645782D12]
        (No symbol) [0x00007FF64561EC65]
        (No symbol) [0x00007FF6456A3B70]
        (No symbol) [0x00007FF645686D83]
        (No symbol) [0x00007FF6456583A8]
        (No symbol) [0x00007FF645659441]
        GetHandleVerifier [0x00007FF645C1262D+4238301]
        GetHandleVerifier [0x00007FF645C4F78D+4488509]
        GetHandleVerifier [0x00007FF645C47A6F+4456479]
        GetHandleVerifier [0x00007FF6458F0606+953270]
        (No symbol) [0x00007FF64578E5DF]
        (No symbol) [0x00007FF6457892B4]
        (No symbol) [0x00007FF6457893EB]
        (No symbol) [0x00007FF645779C24]
        BaseThreadInitThunk [0x00007FFBCC96257D+29]
        RtlUserThreadStart [0x00007FFBCE9CAA58+40]

[11872] Failed to execute script 'main' due to unhandled exception!

**Comment by rodem19** [comment]
저도똑같습니다

**Comment by heon0120** [comment]
이건 클래스카드측에서 navigatoe.webdriver 속성이 true여서 발생한문제입니다. 간단히 셀레늄에서 navigator.webdriver를 false혹은 정의되지 않게금 하시면되요

**Comment by qbaebae** [comment]
> 이건 클래스카드측에서 navigatoe.webdriver 속성이 true여서 발생한문제입니다. 간단히 셀레늄에서 navigator.webdriver를 false혹은 정의되지 않게금 하시면되요

false로 어떻게 바꾸나요??

**Comment by jaco0830** [comment]
> 이건 클래스카드측에서 navigatoe.webdriver 속성이 true여서 발생한문제입니다. 간단히 셀레늄에서 navigator.webdriver를 false혹은 정의되지 않게금 하시면되요

바꾸는 방법을 알려주세요

**Comment by saram0522** [comment]
# navigator.webdriver 속성 숨기기
driver.execute_cdp_cmd('Page.addScriptToEvaluateOnNewDocument', {
    'source': '''
        Object.defineProperty(navigator, 'webdriver', {
            get: () => undefined
        })
    '''
})
이 코드를 추가해보세요

**Comment by saram0522** [comment]
driver이 정의된 줄 아래에 아무데나 복붙하세요

**Comment by hseo0821** [comment]
> driver이 정의된 줄 아래에 아무데나 복붙하세요

아래에 복붙해도

1번 암기학습(매크로)를 선택하셨습니다.
Traceback (most recent call last):
File "C:\Users\github\Downloads\classcard_auto-main2\classcard_auto-main\main.py", line 122, in
driver.find_element(
File "C:\Users\github\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\github\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
self.error_handler.check_response(response)
File "C:\Users\github\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"body > div.mw-1080 > div.p-b-sm > div.set-body.m-t-25.m-b-lg > div.m-b-md > div > a"}
(Session info: chrome=127.0.6533.89); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
GetHandleVerifier [0x00007FF7AA6F9632+30946]
(No symbol) [0x00007FF7AA6AE3C9]
(No symbol) [0x00007FF7AA5A6FDA]
(No symbol) [0x00007FF7AA5F822C]
(No symbol) [0x00007FF7AA5F850C]
(No symbol) [0x00007FF7AA63DCB7]
(No symbol) [0x00007FF7AA61CAAF]
(No symbol) [0x00007FF7AA63B041]
(No symbol) [0x00007FF7AA61C813]
(No symbol) [0x00007FF7AA5EA6E5]
(No symbol) [0x00007FF7AA5EB021]
GetHandleVerifier [0x00007FF7AA82F83D+1301229]
GetHandleVerifier [0x00007FF7AA83BDB7+1351783]
GetHandleVerifier [0x00007FF7AA832A03+1313971]
GetHandleVerifier [0x00007FF7AA72DD06+245686]
(No symbol) [0x00007FF7AA6B758F]
(No symbol) [0x00007FF7AA6B3804]
(No symbol) [0x00007FF7AA6B3992]
(No symbol) [0x00007FF7AA6AA3EF]
BaseThreadInitThunk [0x00007FFAD0887374+20]
RtlUserThreadStart [0x00007FFAD22DCC91+33]

이게 뜨는데 어떡하죠?

**Comment by yabetonee** [comment]
저도 같은 문제입니다

**Comment by rodem19** [comment]
웹페이지가 켜지고나서 어떤학습을선택하더라도
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"body > div.mw-1080 > div.p-b-sm > div.set-body.m-t-25.m-b-lg > div.m-b-md > div > a"}
  (Session info: chrome=127.0.6533.120); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception    
Stacktrace:
        GetHandleVerifier [0x00007FF6087F9642+30946]
        (No symbol) [0x00007FF6087AE3D9]
        (No symbol) [0x00007FF6086A6FDA]
        (No symbol) [0x00007FF6086F822C]
        (No symbol) [0x00007FF6086F850C]
        (No symbol) [0x00007FF60873DCB7]
        (No symbol) [0x00007FF60871CAAF]
        (No symbol) [0x00007FF60873B041]
        (No symbol) [0x00007FF60871C813]
        (No symbol) [0x00007FF6086EA6E5]
        (No symbol) [0x00007FF6086EB021]
        GetHandleVerifier [0x00007FF60892F84D+1301229]
        GetHandleVerifier [0x00007FF60893BDC7+1351783]
        GetHandleVerifier [0x00007FF608932A13+1313971]
        GetHandleVerifier [0x00007FF60882DD16+245686]
        (No symbol) [0x00007FF6087B759F]
        (No symbol) [0x00007FF6087B3814]
        (No symbol) [0x00007FF6087B39A2]
        (No symbol) [0x00007FF6087AA3FF]
        BaseThreadInitThunk [0x00007FF8644F257D+29]
        RtlUserThreadStart [0x00007FF86470AF28+40]
이런 오류 메세지가 뜨면서 실행되지 않습니다 
어떻게 해결해야 하나요?
