### ISSUE TITLE
작동이 안됩니다. 수정 등으로 고칠 방법을 제시해주실 고수분을 찾습니다.

### ISSUE THREAD

**Issue by nomalhuman12** [kimjunsung04/classcard_auto#18]
exe파일을 다운로드 하고 실행을 하였으나,

크롬 드라이브를 불러오고 있습니다 잠시만 기다려주세요!
WARNING:root:Can not find chromedriver for currently installed chrome version.
Traceback (most recent call last):
  File "D:\Desktop\github\classcard_auto\main.py", line 39, in <module>
  File "selenium\webdriver\remote\webdriver.py", line 741, in find_element
  File "selenium\webdriver\remote\webdriver.py", line 347, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 228, in check_response
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: 클래스카드는 Chrome 또는 Safari 브라우저를 사용하세요
Message: unexpected alert open: {Alert text : 클래스카드는 Chrome 또는 Safari 브라우저를 사용하세요}
  (Session info: chrome=128.0.6613.85)
Stacktrace:
        GetHandleVerifier [0x00007FF6E67DB632+29090]
        (No symbol) [0x00007FF6E674E6E9]
        (No symbol) [0x00007FF6E660B1CA]
        (No symbol) [0x00007FF6E66A7196]
        (No symbol) [0x00007FF6E6686493]
        (No symbol) [0x00007FF6E66509B1]
        (No symbol) [0x00007FF6E6651B11]
        GetHandleVerifier [0x00007FF6E6AF881D+3294093]
        GetHandleVerifier [0x00007FF6E6B44403+3604339]
        GetHandleVerifier [0x00007FF6E6B3A2C7+3563063]
        GetHandleVerifier [0x00007FF6E6896F16+797318]
        (No symbol) [0x00007FF6E675986F]
        (No symbol) [0x00007FF6E6755454]
        (No symbol) [0x00007FF6E67555E0]
        (No symbol) [0x00007FF6E6744A7F]
        BaseThreadInitThunk [0x00007FF942357374+20]
        RtlUserThreadStart [0x00007FF94435CC91+33]

[16788] Failed to execute script 'main' due to unhandled exception!

이와 같은 에러가 뜹니다.
혹시몰라 폴더도 다운받아 requirements.txt의 값을 넣고 실행해 보았지만,

WARNING:root:Can not find chromedriver for currently installed chrome version.
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\classcard_auto-2.1.0\main.py", line 39, in <module>
    tag_id = driver.find_element(By.ID, "login_id")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 228, in check_response
    raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: 클래스카드는 Chrome 또는 Safari 브라우저를 사용 하세요
Message: unexpected alert open: {Alert text : 클래스카드는 Chrome 또는 Safari 브라우저를 사용하세요}
  (Session info: chrome=128.0.6613.85)
Stacktrace:
        GetHandleVerifier [0x00007FF6E67DB632+29090]
        (No symbol) [0x00007FF6E674E6E9]
        (No symbol) [0x00007FF6E660B1CA]
        (No symbol) [0x00007FF6E66A7196]
        (No symbol) [0x00007FF6E6686493]
        (No symbol) [0x00007FF6E66509B1]
        (No symbol) [0x00007FF6E6651B11]
        GetHandleVerifier [0x00007FF6E6AF881D+3294093]
        GetHandleVerifier [0x00007FF6E6B44403+3604339]
        GetHandleVerifier [0x00007FF6E6B3A2C7+3563063]
        GetHandleVerifier [0x00007FF6E6896F16+797318]
        (No symbol) [0x00007FF6E675986F]
        (No symbol) [0x00007FF6E6755454]
        (No symbol) [0x00007FF6E67555E0]
        (No symbol) [0x00007FF6E6744A7F]
        BaseThreadInitThunk [0x00007FF942357374+20]
        RtlUserThreadStart [0x00007FF94435CC91+33]

와 같은 에러가 뜨고, 그 즉시 콘솔창과 크롬창이 꺼집니다.
혹시 이 문제에 대한 해법을 알고 계신 고수분들 계신가요?

**Comment by lanzarote0tr** [comment]
#21 에서 고수분이 오셨군요.
