### ISSUE TITLE
프로그램이 진행되다, 학습유형을 선택하고나서 다음과 같은 오류는 무엇인가요?

### ISSUE THREAD

**Issue by josun1392** [kimjunsung04/classcard_auto#3]
Traceback (most recent call last):
  File "C:\Users\user\OneDrive\바탕 화면\새파일\classcard_auto-main\main.py", line 77, in <module>
    cash_d = driver.find_element_by_xpath(
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 520, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/div/div[1]/div[1]/div[2]"}
  (Session info: chrome=96.0.4664.45)

![image](https://user-images.githubusercontent.com/65928110/146317511-9d9edf8d-8f4b-4c2e-bb54-69ef30b7ec99.png)

+ xpath 선택자에 대해 일치하는 요소가 없다는 것 같기는 하다만... 뭘 건들여야할지 모르겠네요 ㅠㅜ

**Comment by ghost** [comment]
main.py 에서 77줄부터 81줄까지 지운 뒤 이 코드를 추가하세요
```python
html = BeautifulSoup(driver.page_source, 'html.parser')
cards_ele = html.find('div', class_='flip-body')
num_d = len(cards_ele.find_all('div', class_='flip-card')) + 1
```
그래도 안되면 세트URL 남겨주세요

**Comment by josun1392** [comment]
오! 되네요 ! 감사합니다 ~
